runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript
- url: /css
  static_dir: css

- url: /.*
  script: main.app

- url: /view/.*
  script: user_profile.app
  login: required

libraries:
  - name: jinja2
    version: latest
